"""add lab_report table

Revision ID: 24e4eb027d43
Revises: d9e5f2a1b7c4
Create Date: 2026-08-26 07:25:58.931404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e4eb027d43'
down_revision: Union[str, Sequence[str], None] = 'd9e5f2a1b7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_report',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('report_status', sa.String(length=50), nullable=False),
    sa.Column('report_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_report_patient_id'), 'lab_report', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_report_patient_id'), table_name='lab_report')
    op.drop_table('lab_report')
    # ### end Alembic commands ###
