"""add created_at to lab_report

Revision ID: 4798f692cbc3
Revises: 24e4eb027d43
Create Date: 2026-08-26 08:03:09.988202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4798f692cbc3'
down_revision: Union[str, Sequence[str], None] = '24e4eb027d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_report', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab_report', 'created_at')
    # ### end Alembic commands ###
